version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300 # Check every 5 minutes
      - WATCHTOWER_CLEANUP=true # Remove old images
      - WATCHTOWER_INCLUDE_STOPPED=true # Include stopped containers
      # Point to local registry instead of Docker Hub
      - WATCHTOWER_REGISTRY_USE_LOCAL=true
      - WATCHTOWER_REGISTRY=localhost:5000
    command: --debug csl-certificates
    networks:
      - csl-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8080/v1/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  csl-network:
    external: true
