#!/usr/bin/env bash
#
# Thin-overlay production deploy, with flattening built in.
#
# Releases are not built from the root Dockerfile — that path goes through
# Ansible/GitHub Actions and is slow. Day-to-day we build a thin overlay on top
# of whatever tag is currently deployed, which is fast because the expensive
# layers (PHP extensions, composer install) are already there.
#
# THE PROBLEM THIS SOLVES
# Every overlay adds layers, and they accumulate forever. On 2026-08-07 the
# image reached 125 layers against Docker's hard limit of 127, and a deploy
# failed outright with "max depth exceeded" — two more deploys and shipping
# would have been impossible. Nothing warns you as you approach it.
#
# So every build here ends by collapsing the filesystem into a single layer via
# `COPY --from` over a scratch base. Depth stays at ~3 forever instead of
# climbing. The cost is roughly ten seconds per deploy.
#
# A scratch base inherits NO configuration — no ENV, ENTRYPOINT, WORKDIR,
# EXPOSE or HEALTHCHECK. Those are read back off the base image with
# `docker inspect` and re-emitted, rather than hand-copied, so they cannot
# silently drift. Getting this wrong produces an image that builds fine and
# then fails to boot.
#
# USAGE (run on the VPS, from a source tree at the commit you want to ship)
#   ./deploy/overlay-deploy.sh <tag> [path ...]
#
#   ./deploy/overlay-deploy.sh branding-3936026 app database/migrations
#   ./deploy/overlay-deploy.sh hotfix-abc1234            # defaults, see below
#
# Copy only what changed. Shipping `app` alone is normal; add
# `database/migrations` when there is a migration (the entrypoint runs them),
# `routes` when routes change, `config` when config does.
#
# ROLLBACK
#   The previous override is saved as docker-compose.override.yml.bak-<tag>-<ts>.
#   Restore it and re-run `docker compose up -d app scheduler queue`.
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/csl-certification-rest-api}"
IMAGE_REPO="${IMAGE_REPO:-registry.olkoo.com/csl/csl-certification-rest-api}"
SERVICES="${SERVICES:-app scheduler queue}"
HEALTH_URL="${HEALTH_URL:-https://certification.csl-brands.com/api/onboarding/validate-domain}"
# Kept well under Docker's 127 so a failure is a loud bug, not a cliff edge.
MAX_LAYERS="${MAX_LAYERS:-20}"

TAG="${1:-}"
if [[ -z "$TAG" ]]; then
    echo "usage: $0 <tag> [path ...]" >&2
    exit 64
fi
shift

PATHS=("$@")
if [[ ${#PATHS[@]} -eq 0 ]]; then
    PATHS=(app config database lang resources routes)
fi

SRC_DIR="$(pwd)"
IMAGE="${IMAGE_REPO}:${TAG}"

step() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
die()  { printf '\033[31mFAILED: %s\033[0m\n' "$*" >&2; exit 1; }

# ── Resolve the base: whatever is deployed right now ──────────────────────────
step "Resolving current production image"
BASE="$(grep -oE "${IMAGE_REPO}:[A-Za-z0-9._-]+" "${APP_DIR}/docker-compose.override.yml" | head -1)" \
    || die "could not read the current image from ${APP_DIR}/docker-compose.override.yml"
[[ -n "$BASE" ]] || die "no image found in the override file"
echo "base:   $BASE"
echo "new:    $IMAGE"
echo "copying: ${PATHS[*]}"

[[ "$BASE" == "$IMAGE" ]] && die "tag ${TAG} is already deployed; pick a new tag"

for p in "${PATHS[@]}"; do
    [[ -e "${SRC_DIR}/${p}" ]] || die "path '${p}' does not exist in ${SRC_DIR}"
done

# ── Generate the Dockerfile, config included ─────────────────────────────────
step "Generating flattening Dockerfile from ${BASE}"
docker image inspect "$BASE" --format '{{json .Config}}' > /tmp/.overlay-cfg.json \
    || die "base image ${BASE} not present locally — docker pull it first"

COPIES=""
for p in "${PATHS[@]}"; do
    COPIES+="COPY --chown=www-data:www-data ${p} /var/www/html/${p}"$'\n'
done

BASE="$BASE" COPIES="$COPIES" python3 - > "${SRC_DIR}/Dockerfile.overlay-flat" <<'PY'
import json, os, shlex

cfg = json.load(open('/tmp/.overlay-cfg.json'))
out = [
    '# GENERATED by deploy/overlay-deploy.sh -- do not edit, do not commit.',
    '# Stage 1 applies the change; stage 2 flattens it to a single layer so the',
    '# overlay chain cannot grow toward Docker 127-layer limit.',
    f"FROM {os.environ['BASE']} AS src",
    os.environ['COPIES'].rstrip(),
    '',
    'FROM scratch',
    'COPY --from=src / /',
    '',
    '# A scratch base inherits none of this; re-emitted verbatim from the base.',
]
for entry in cfg.get('Env') or []:
    key, _, value = entry.partition('=')
    out.append(f'ENV {key}={shlex.quote(value)}')

if cfg.get('WorkingDir'):
    out.append(f"WORKDIR {cfg['WorkingDir']}")

ports = sorted((cfg.get('ExposedPorts') or {}).keys())
if ports:
    out.append('EXPOSE ' + ' '.join(p.split('/')[0] for p in ports))

hc = cfg.get('Healthcheck') or {}
if hc.get('Test'):
    test = hc['Test']
    shell = test[1] if test[0] == 'CMD-SHELL' else ' '.join(test[1:])
    out.append(
        'HEALTHCHECK --interval={}s --timeout={}s --start-period={}s --retries={} CMD {}'.format(
            hc.get('Interval', 30_000_000_000) // 10**9,
            hc.get('Timeout', 10_000_000_000) // 10**9,
            hc.get('StartPeriod', 0) // 10**9,
            hc.get('Retries', 3),
            shell,
        )
    )

if cfg.get('User'):
    out.append(f"USER {cfg['User']}")
if cfg.get('Entrypoint'):
    out.append('ENTRYPOINT ' + json.dumps(cfg['Entrypoint']))
if cfg.get('Cmd'):
    out.append('CMD ' + json.dumps(cfg['Cmd']))

print('\n'.join(out))
PY

# ── Build ────────────────────────────────────────────────────────────────────
step "Building ${IMAGE}"
docker build -f "${SRC_DIR}/Dockerfile.overlay-flat" -t "$IMAGE" "$SRC_DIR" \
    || die "build failed"

LAYERS="$(docker image inspect "$IMAGE" --format '{{len .RootFS.Layers}}')"
echo "layers: ${LAYERS} (was $(docker image inspect "$BASE" --format '{{len .RootFS.Layers}}'))"
[[ "$LAYERS" -le "$MAX_LAYERS" ]] \
    || die "flattening did not work — ${LAYERS} layers, expected <= ${MAX_LAYERS}"

# ── Smoke-test the image before it goes anywhere near production ─────────────
step "Verifying the image boots"
docker run --rm --entrypoint bash "$IMAGE" -c '
    set -e
    php -v > /dev/null
    php artisan --version > /dev/null
    test -f vendor/autoload.php
    test -x /usr/local/bin/entrypoint.sh
' || die "image is broken — config or filesystem did not survive the flatten"
echo "php, artisan, vendor and entrypoint all present"

# ── Ship ─────────────────────────────────────────────────────────────────────
step "Pushing ${IMAGE}"
docker push "$IMAGE" || die "push failed"

step "Repointing ${SERVICES}"
BACKUP="${APP_DIR}/docker-compose.override.yml.bak-${TAG}-$(date +%s)"
cp "${APP_DIR}/docker-compose.override.yml" "$BACKUP"
echo "backup: $BACKUP"
sed -i "s|${IMAGE_REPO}:[A-Za-z0-9._-]*|${IMAGE}|g" "${APP_DIR}/docker-compose.override.yml"

# shellcheck disable=SC2086
(cd "$APP_DIR" && docker compose up -d $SERVICES) || {
    echo "rolling back the override" >&2
    cp "$BACKUP" "${APP_DIR}/docker-compose.override.yml"
    die "compose up failed — override restored, re-run 'docker compose up -d ${SERVICES}'"
}

# ── Verify ───────────────────────────────────────────────────────────────────
step "Waiting for health"
for _ in $(seq 1 60); do
    status="$(docker inspect --format '{{.State.Health.Status}}' csl-certification-rest-api 2>/dev/null || echo starting)"
    [[ "$status" == "healthy" ]] && break
    sleep 5
done
[[ "$status" == "healthy" ]] || die "app did not become healthy — restore ${BACKUP} and re-run compose up"

docker ps --filter name=csl-certification-rest-api --format '{{.Names}}\t{{.Image}}\t{{.Status}}' | head -5

step "Smoke-testing production"
code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 25 -X POST "$HEALTH_URL" \
    -H 'Content-Type: application/json' \
    -d '{"domain":"deploy-probe.csl-brands.com","type":"subdomain"}')"
echo "${HEALTH_URL} -> ${code}"
[[ "$code" == "200" ]] || die "production is not answering 200 — restore ${BACKUP} and re-run compose up"

rm -f "${SRC_DIR}/Dockerfile.overlay-flat" /tmp/.overlay-cfg.json

step "Deployed ${TAG}"
cat <<EOF

  image:    ${IMAGE}
  layers:   ${LAYERS}
  services: ${SERVICES}

  rollback:
    cp ${BACKUP} ${APP_DIR}/docker-compose.override.yml
    cd ${APP_DIR} && docker compose up -d ${SERVICES}
EOF
